### ISSUE TITLE
404 on Homepage

### ISSUE THREAD

**Issue by thezenmonkey** [Martimiz/silverstripe-languageprefix#26]
I'm currently testing the prefixer but the homepage on the default langues is coming up as "Page not found." It works fine without the module. I'm using ss3.4 and here is my mysite/_config/config.yml

``` yaml
i18n :
  common_locales:
    en_CA: 
      name: 'English (Canada)'
      native: 'English (Canada)'
    en_AU: 
      name: 'English (Australia)'
      native: 'English (Australia)'

Translatable:
  enforce_global_unique_urls: false

---
Name: languageprefix-config

---
prefixconfig:
  locale_prefix_map:
    # 'en_GB': uk
    'en_US': us
    'en_CA': ca
  enable_duplicate_urlsegments: true
  disable_prefix_for_default_lang: true
```

Default locale is configured in _config.php as 

``` php
i18n::set_locale('en_GB');
Translatable::set_default_locale('en_GB');
```

 Any suggestions?

**Comment by Martimiz** [comment]
Hmm that's strange... I'll try and reproduce it. Would be great if you could look into it as well if you have the time that is :)

Btw: which version of LanguagePrefix and Translatable are you using?

**Comment by Martimiz** [comment]
I'm sorry, I couldn't reproduce this problem.

Below is what I did.  I also added the settings I used - which are almost the same as yours, the only thing different is en_AU in the prefix map instead of en_CA, because I had created Australian translations instead of Canadian :)

I did the following:
- composer create-project silverstripe/installer www
- composer require silverstripe/translatable 2.2.0
- composer require martimiz/silverstripe-languageprefix v3.0.0
- add the _config.php settings
- dev/build?flush
- add the config.yml settings
- ?flush=all
- created en_AU translations
- tested homepage www/mysite.dev/ and www/mysite.dev/au/ -> both found == ok
- tested www/mysite.dev/en_GB/  -> not found == ok
- tested other translations -> ok 

```
i18n::set_locale('en_GB');
Translatable::set_default_locale('en_GB');
```

```
i18n:
  common_locales:
    en_CA: 
      name: 'English (Canada)'
      native: 'English (Canada)'
    en_AU: 
      name: 'English (Australia)'
      native: 'English (Australia)'
Translatable:
  enforce_global_unique_urls: false
---
Name: languageprefix-config
---
prefixconfig:
  locale_prefix_map:
    # 'en_GB': uk
    'en_US': us
    'en_AU': au
  enable_duplicate_urlsegments: true
  disable_prefix_for_default_lang: true
```
